# Generated by Django 4.1.3 on 2022-11-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='enunciado',
            field=models.CharField(default='resposta correta', max_length=1000),
            preserve_default=False,
        ),
    ]
