# Generated by Django 4.1.3 on 2022-12-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_remove_tabela_pergunta_alter_pergunta_enunciado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela',
            name='pecas',
            field=models.CharField(max_length=50),
        ),
    ]
