# Generated by Django 4.1.3 on 2022-12-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_alter_tabela_pecas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela',
            name='pecas',
            field=models.CharField(max_length=100),
        ),
    ]
